version: '3.8'
services:
  base-microservice:
    image: base-microservice:latest
    container_name: base-microservice
    environment:
      - SERVICE
      - SIDECAR_ONE_IP = base-adapter:8081
    ports:
      - "8080:8080"